iniciador/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from . import views
#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^website/', views.WebsiteView.as_view(), name='website'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^api/', include('members.api.urls', namespace='api-members')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

members/api/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^members$', views.MemberList.as_view(), name='member-list'),
    url(r'^members/(?P<pk>\d+)$', views.MemberDetail.as_view(), name='member-detail'),
)

members/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^list/$', views.MemberListView.as_view(), name='member_list'),
    #(?P<username>\w+)
    url(r'^group/(?P<name>\w+)/$', views.GroupView.as_view(), name='group'),
    url(r'^member/(?P<id>\w+)/$', views.UserAPI.as_view(), name='user-api'),
    url(r'^list/json/$', views.UserListAPI.as_view(), name='user-list-api'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^all/$', views.AllMembersView.as_view(), name='all-members'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/members/password/reset/done/'}, name='password_reset'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/members/password/done/'}, name='password_reset_confirm'),
    url(r'^password/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^revision/(?P<username>.+)/(?P<hash>\w+)/(?P<status>\w+)/$', views.ReviewView.as_view(), name='review'),
    url(r'^signup/thanks/$', views.ThanksView.as_view(), name='thanks'),

)

members/models.py
from datetime import date

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from model_utils import Choices
from model_utils.models import TimeStampedModel

from django.contrib.auth.models import User

@python_2_unicode_compatible
class Member(TimeStampedModel):
    STATUS = Choices(
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('pending', 'Pending'),
        ('unknown', 'Unknown'),
    )

    photo = models.FileField(upload_to='photos/', null=True, blank=True)
    id_iniciador = models.IntegerField(null=True, blank=True)
    user = models.OneToOneField(User, related_name='member')
    bio = models.TextField(blank=True)
    phone = models.CharField(blank=False, max_length=100)
    role = models.CharField(blank=True, max_length=100)
    status = models.CharField(blank=False, choices=STATUS, max_length=100)
    last_activity = models.DateField(null=False, default=date.today)

    profiles = models.ManyToManyField('Profile', blank=True)
    secondary_emails = models.ManyToManyField('Email', blank=True)
    groups = models.ManyToManyField('Group', null=False)

    def __str__(self):
        return u"{self.user.first_name} {self.user.last_name}".format(self=self)

    def owner(self):
        return self.user

@python_2_unicode_compatible
class Profile(models.Model):
    NETWORK = Choices(
        ('linkedin', 'Linkedin'),
        ('twitter', 'Twitter'),
        ('other', 'Other'),
    )

    url = models.URLField(primary_key=True)
    name = models.CharField(max_length=200, blank=True)
    network = models.CharField(null=True, choices=NETWORK, max_length=100)

    def __str__(self):
        return self.pk

@python_2_unicode_compatible
class Group(models.Model):
    name = models.CharField(null=False, blank=False, max_length=100, primary_key=True)
    email = models.ForeignKey(
        'Email', related_name='email_set', null=True, blank=True)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Email(models.Model):
    email = models.EmailField(primary_key=True, null=False)

    def __str__(self):
        return self.pk

members/forms.py
from django import forms
from django.conf import settings

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives

from .models import Member
from .models import Group
from .models import Email
from .models import Profile
from django.contrib.auth.models import User

'''class SignupForm(forms.ModelForm):
    class Meta:
       model = Member
       fields = [
           'user', 'photo', 'bio', 'phone', 'role', 'status',
           'profiles', 'secondary_emails', 'groups'
       ]'''

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    photo = forms.FileField(required=True)
    bio = forms.CharField(max_length=400, required=True)
    linkedin = forms.URLField(max_length=300, required=True)
    twitter = forms.URLField(max_length=300, required=True)
    primary_email = forms.EmailField(required=True)
    secondary_emails = forms.CharField(max_length=400, required=False)
    phone = forms.CharField(max_length=200, required=True)
    role = forms.CharField(max_length=200, required=True)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), required=True)

    def save(self):

        data = self.cleaned_data
        
        u = User.objects.create(
            email = data.get("primary_email"),
            first_name = data.get("first_name"),
            last_name = data.get("last_name"),
            username = data.get("primary_email").split("@")[0][:30],
        )
        password = User.objects.make_random_password()
        u.set_password(password)
        u.save()

        m = Member.objects.create(
            user = u,
            bio = data.get('bio'),
            phone = data.get('phone'),
            role = data.get('role'),
            status = 'pending',
            photo = data.get('photo')
        )

        #import ipdb; ipdb.set_trace()
        groups = data.get("groups")

        for g in groups:
            g = Group.objects.get(name = g)
            m.groups.add(g)

        emails = data.get('secondary_emails');
        if emails:
            for e in emails.split(','):
                e, created = Email.objects.get_or_create(email = e.strip())
                m.secondary_emails.add(e)

        linkedin = data.get('linkedin')
        l, created = Profile.objects.get_or_create(url = linkedin, network = 'linkedin')
        m.profiles.add(l)

        twitter = data.get('twitter')
        t, created = Profile.objects.get_or_create(url = twitter, network = 'twitter')
        m.profiles.add(t)

        # Send mail to user
        #import ipdb; ipdb.set_trace()
        mail_to = settings.ADMIN_EMAIL if settings.DEBUG else data.get("primary_email")

        msg = EmailMultiAlternatives(
            subject = "Solicitud de alta",
            from_email = settings.FROM_EMAIL,
            to = [mail_to]
        )
        msg.tags = ["iniciador", "alta"]
        msg.metadata = {'user_id': m.id}
        msg.template_name = "alta-iniciador"
        msg.global_merge_vars = {
            'NAME': data.get("first_name"),
            'PASSWORD': password,
            'USERNAME': data.get("primary_email").split("@")[0][:30],
            #'WEBSITE': "<a href='" + data.get('linkedin') + "/*|TRACKINGNO|*'>Linkedin</a>"
        }
        print "Mail sent to:" + mail_to
        msg.send()

        # Send mail to iniciador
        mail_to = settings.ADMIN_EMAIL if settings.DEBUG else settings.FROM_EMAIL

        msg = EmailMultiAlternatives(
            subject = "Nueva solicitud de alta",
            from_email = settings.FROM_EMAIL,
            to = [mail_to]
        )
        msg.tags = ["iniciador", "alta", "gerencia", "user-" + str(m.id)]
        msg.metadata = {'user_id': m.id}
        msg.template_name = "aviso-a-gerencia-alta"
        msg.global_merge_vars = {
            'NAME': data.get("first_name"),
            'LASTNAME': data.get("last_name"),
            'UID': m.id,
            'SERVER': settings.SERVER,
            #'WEBSITE': "<a href='" + data.get('linkedin') + "/*|TRACKINGNO|*'>Linkedin</a>"
        }
        print "Mail sent to:" + mail_to
        msg.send()

        #response = msg.mandrill_response[0]
        #mandrill_id = response['_id']

    def clean_primary_email(self):
        cleaned_data = super(SignupForm, self).clean()
        primary_email = cleaned_data.get("primary_email")

        try:
            user = User.objects.get(email = primary_email)
        except User.DoesNotExist:
            user = None

        if user:
            self.add_error('primary_email', "Ya existe un usuario con este correo, si has escrito tu email personal ponte en contacto con gerencia@iniciador.com")
        else:
            return primary_email

    '''
    TODO: Validate email properly formed
    def clean_secondary_emails(self):

    TODO: Validate phone numbers
    '''

members/api/views.py
from rest_framework import generics

from ..models import Member
from .serializers import UserSerializer, GroupSerializer, MemberSerializer

class MemberList(generics.ListAPIView):

    queryset = Member.objects.all()
    serializer_class = MemberSerializer
    model = Member

    '''def get_queryset(self):
        args = self.get_context_data(**kwargs)
        import ipdb; ipdb.set_trace()

        return Member.objects.filter(user__username = args["username"])'''


class MemberDetail(generics.RetrieveUpdateAPIView):
    #import ipdb; ipdb.set_trace()
    #queryset = Member.objects.get(user__username='hhkaos')
    queryset = Member.objects.all()
    serializer_class = MemberSerializer
    model = Member

members/views.py
from datetime import date
import hashlib

from django.shortcuts import render
from braces.views import LoginRequiredMixin

from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.models import User, Group

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import redirect

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives

from django.shortcuts import render
from django.shortcuts import get_object_or_404
#from django.shortcuts import get_or_create
from django.views import generic
from django.http import JsonResponse



from .forms import SignupForm
from .models import Member
from .models import Group
from .models import Email
from .models import Profile


class SignupView(generic.FormView):
    form_class = SignupForm
    template_name = 'members/signup.html'

    def post(self, request, *args, **kwargs):
        form = SignupForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            #import ipdb; ipdb.set_trace()
            # Save photo
            context = request.POST
            m = Member.objects.get(user__username=context.get('primary_email').split("@")[0][:30])

            # Save profiles
            num_websites = context.get('num_websites');
            for i in range(1, int(num_websites) + 1):
                name = context.get('website_name_'+str(i))
                url = context.get('website_url_'+str(i))
                if name and url:
                    p, created = Profile.objects.get_or_create(url = url.strip(), name = name)
                    m.profiles.add(p)

            m.save()

            return HttpResponseRedirect(reverse('members:thanks')) # Redirect after POST
        else:
            #import ipdb; ipdb.set_trace()
            context = self.get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        form = SignupForm()
        context = self.get_context_data(**kwargs)
        context['form'] = form

        return self.render_to_response(context)
        '''return render(request, 'members/signup2.html', {
            'form': form,
        })'''

class ThanksView(generic.TemplateView):
    template_name = 'members/thanks.html'

class DashboardView(generic.TemplateView):
    template_name = 'members/dashboard.html'

class MemberListView(generic.TemplateView):
    template_name = 'members/member_list.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['members'] = Member.objects.all()

        return self.render_to_response(context)

class ReviewView(generic.TemplateView):
    template_name = 'members/review.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        u = Member.objects.get(user__username = context.get('username'))
        valid_hash = hashlib.sha224(str(u.last_activity) + str(u.user.id)).hexdigest()

        #b8b60ecfb50dbe3aa504c776934e2bd3a3b5e67670e6b1bbabe4d426 == 1/08/2014

        # Check if usernanme - hash is valid
        if context.get('hash') == valid_hash:
            context['valid'] = True
            status = context.get('status')
            #import ipdb; ipdb.set_trace()
            if status == 'valid':
                u.status = 'active'
                u.last_activity = date.today()
                u.save()
            elif status == 'invalid':
                pass
            elif status == 'unsuscribe':
                u.status = 'inactive'
                u.last_activity = date.today()
                u.save()
                #TODO: send an email to the organization
            else:
                pass
        else:
            context['valid'] = False

        return self.render_to_response(context)



#TODO: Add decorator
class ProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'members/profile.html'

    login_url = "/members/login/"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

class ResetPassView(generic.TemplateView):
    template_name = 'registration/reset_password.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['request'] = "GET"
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['request'] = "POST"
        return self.render_to_response(context)

class GroupView(generic.TemplateView):
    template_name = 'members/group.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['g'] = get_object_or_404(Group, name=context.get('name'))
        return self.render_to_response(context)

class AllMembersView(generic.TemplateView):
    template_name = 'members/all_members.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['groups'] = Group.objects.all().order_by("name")
        context['members'] = Member.objects.all()

        return self.render_to_response(context)

class UserAPI(generic.TemplateView):
    template_name = 'members/userApi.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        m = get_object_or_404(Member, id_iniciador=context['id'])
        context['member'] = m

        return self.render_to_response(context)

class UserListAPI(generic.TemplateView):
    template_name = 'members/userListApi.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['members'] = Member.objects.all()

        return self.render_to_response(context)

members/templates/members/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block breadcumb %}
  <!--<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">Inicio</a></li>
    <li class="active">Dashboard</a>
  </ol>-->
{% endblock %}


{% block body %}


<script type="text/javascript" src="https://assets.yammer.com/assets/platform_embed.js"></script>
<script>
$(document).ready(function(){
  $('#myTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })
  yam.connect.embedFeed({
    container: "#embedded-feed",
    network: "reiniciador.com",
    feedType: "group",
    feedId: "all"});
});
</script>




<a class="btn btn-warning pull-right" href="{% url 'members:all-members' %}">Conoce quienes son los demás organizadores</a>
  <div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Yammer</a></li>
      <li role="presentation" ><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Recursos</a></li>
      <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Sistemas</a></li>
      <!--<li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>-->
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane " id="home">
        <ol>
          <li>Échale un ojo al: <a href="https://drive.google.com/folderview?id=0BzSfMwbfluEpMTEzN2FiN2QtODBlNy00ZjliLWE4ODUtNTQ0NTUwMjA0NzAx&usp=drive_web#">Manual de operaciones</a> (mientras terminamos el <i>Welcome pack</i>)</li>
        </ol>
      </div>
      <div role="tabpanel" class="tab-pane active" id="profile">
        <p>Para poder acceder a Yammer necesitas una cuenta de correo @reiniciador.com (que te crearán en breve desde gerencia). Preséntate en la cafetería a los demás cuando tengas tu cuenta!</p>
        <div id="embedded-feed" style="height:800px;width:100%;"></div>

      </div>
      <div role="tabpanel" class="tab-pane" id="messages">
        <ul>
          <li><a href="http://iniciador.com">Iniciador.com</a>: Página oficial de Iniciador (eventos, noticias, etc.)</li>
          <li><a href="https://www.yammer.com/reiniciador.com/?show_login=true">Yammer: Reiniciador.com</a>: Red social privada de la comunidad</li>
          <li><a href="https://www.linkedin.com/groups/Iniciador-Grupo-emprendedores-150876?gid=150876&mostPopular=&trk=tyah&trkInfo=tarId%3A1418692247943%2Ctas%3Ainiciador%2Cidx%3A3-1-7">Grupo abierto de Linkedin</a>: Grupo abierto de Iniciador en Linkedin</li>
          <li><a href="https://www.linkedin.com/groups?gid=8182411&mostPopular=&trk=tyah&trkInfo=tarId%3A1418692058358%2Ctas%3Ainiciador%20te%2Cidx%3A1-2-2">Iniciador Team (Linkedin)</a> - Proximamente sustituido por Yammer</li>
        </ul>
      </div>
      <!--<div role="tabpanel" class="tab-pane" id="settings">...</div>-->
    </div>

  </div>


{% endblock %}

members/templates/members/group.html
{% extends "base.html" %}
{% load staticfiles %}

{% block breadcumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Inicio</a></li>
  <li class="active">Iniciador {{g.name}}</a>
</ol>
{% endblock %}

{% block body %}
  <h1>Iniciador {{g.name}}</h1>
  <p>Detalles del grupo</p>

{% endblock %}

members/templates/members/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
<h1>Comunidad Iniciador</h1>
<div class="pull-right text-center" id="community">
  <img src="{% static 'members/img/global-meeting.png' %}" class="img-thumbnail mb1">
  <p>
    <a target="_blank" href="https://www.youtube.com/watch?v=9iv1qJ0mxpg">
      26/09/2014 - Global Meeting #GMInicador
    </a>
  </p>
</div>
<p>Iniciador es una fundación tiene como objetivo fomentar y facilitar el emprendimiento en el mundo.</p>
<p><strong>La comunidad la forman {{num_groups}} equipos que suman <a href="{% url 'members:member_list' %}">{{num_members}} emprendedores</a></strong>  y que organizan voluntariamente eventos para emprendedores periódicamente en diferentes ciudades.
{% comment %}
<p>Aquí puedes consultar todos equipos que forman en Iniciador:</p>

  <form class="form-inline" id="group-detail" target="_blank">

    <select class="form-control mb1" >
    {% for c in groups %}

      <option value="{% url 'members:group' c %}">Iniciador {{c}}</option>
    {% endfor %}
    </select>
    <button class="form-control mb1" >Ver</button>
  </form>
{% endcomment %}
<p>Si en tu ciudad no hay Iniciador o quieres unirte a alguna ciudad puede <a href="{% url 'members:signup' %}">solicitar el alta aquí</a>.</p>
<h2>Razones para ser organizador en Iniciador</h2>
<p>Las personas que mejor pueden explicarte los motivos ser organizador son los propios miembros de la comunidad, así que aquí te dejamos unos vídeos que han hecho ellos mismos.</p>
<ul id="why-iniciador">
  <li>
    <iframe width="200" height="113" src="//www.youtube.com/embed/KBje7ko4UHo" frameborder="0" allowfullscreen></iframe>
    <p>Ángel María - Iniciador Madrid</p>
  </li>
  <li>
    <iframe width="200" height="113" src="//www.youtube.com/embed/8HAY7ynRFB0" frameborder="0" allowfullscreen></iframe>
    <p>Raúl Jiménez - Iniciador Madrid</p>
  </li>
</ul>
{% endblock %}

members/templates/members/signup.html
{% extends "base.html" %}
{% load staticfiles %}

{% block custom_js %}
<script src="{% static 'members/js/signup.js' %}" /></script>
{% endblock %}

{% block breadcumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Inicio</a></li>
  <li class="active">Solicitud de alta en Iniciador</a>
  </ol>
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-12">
      <h1>Solicitud de alta de Iniciador</h1>
      <p>En este formulario te pedimos algunos datos de contacto, otros datos sobre tí (información que compartimos entre todos los miembros) e información del grupo/iniciativa al que te quieres incorporar</p>
    </div>
  </div>

  <form action="" method="post" class="row mb2" id="signup-form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="col-md-6">
      <div class="box">
        <h2>Sobre ti</h2>
        <p class="short">
          <label for="id_first_name">Nombre*:</label>
          <input type="text" value="{{form.first_name.value|default:""}}" class="form-control" id="id_first_name" name="first_name" placeholder="Raúl" required></input>
          {{form.first_name.errors}}
        </p>
        <p class="short">
          <label for="id_last_name" >Apellidos*:</label>
          <input type="text" value="{{form.last_name.value|default:""}}" class="form-control" id="id_last_name" name="last_name" placeholder="Jiménez Ortega" required></input>
          {{form.last_name.errors}}
        </p>
        <p>

          <p class="short">
            <label for="id_photo" >Foto*:</label>
            <span class="btn btn-sm btn-info btn-file">
              Subir fichero
              <input id="id_photo" name="photo" type="file" required>
            </span>
            {{form.photo.errors}}

          </p>
          <p class="short">
            <label for="id_bio" class="pull-left">Motivación*:</label>
            &nbsp;<textarea cols="40" id="id_bio" name="bio" rows="10" class="form-control" placeholder="¿Qué es lo que te ha motivado a unirte a Iniciador?" required>{{form.bio.value|default:""}}</textarea>
            {{form.bio.errors}}
          </p>

          <p>
            <label for="id_profiles">Perfiles y sitios:</label>
            <ul id="profiles">
              <li class="short">
                <label for="id_linkedin">Linkedin*:</label>
                <input id="id_linkedin" maxlength="200" name="linkedin" type="text" class="form-control" placeholder="http://es.linkedin.com/in/jimenezortegaraul" value="{{form.linkedin.value|default:""}}" required data-toggle="tooltip" data-placement="bottom" title="Revisa que la URL esté bien escrita">
                {{form.linkedin.errors}}
              </li>
              <li class="short">
                <label for="id_twitter">Twitter*:</label>
                <input id="id_twitter" maxlength="200" name="twitter" type="text" class="form-control" placeholder="http://twitter.com/hhkaos" value="{{form.twitter.value|default:""}}" required  data-toggle="tooltip" data-placement="bottom" title="Revisa que la URL esté bien escrita">
                {{form.twitter.errors}}
              </li>
              <li>
                <hr>
                <p><span class="short">Otros sitios:</span> <span class="btn btn-sm btn-info" id="add-website">+Añadir</span></p>
                <input type="hidden" id="num_websites" name="num_websites" value="1">
                <ul id="other_profiles">
                  <li class="short" data-toggle="tooltip" data-placement="bottom" title="Comprueba los datos">
                    <label for="id_website_name_1">Nombre</label>
                    <input id="id_website_name_1" maxlength="100" name="website_name_1" type="text" placeholder="Blog" class="form-control">
                    <label for="id_website_url_1">URL</label>
                    <input id="id_website_url_1" maxlength="100" name="website_url_1" type="text" placeholder="http://rauljimenez.info" class="form-control">
                  </li>
                </ul>
              </li>
            </ul>

          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="box mb1">
          <h2>Datos de contacto</h2>
          <p class="short">
            <label for="id_primary_email">Email personal*:</label>
            <input value="{{form.primary_email.value|default:""}}"type="text" id="id_primary_email" name="primary_email" placeholder="hhkaos@gmail.com" class="form-control" required  data-toggle="tooltip" data-placement="bottom" title="Revisa que el correo esté bien escrito"></input>
            <small>Indica un correo que siempre vayas a comprobar (por ej: Gmail)</small>
            {{form.primary_email.errors}}
          </p>
          <p class="short">
            <label for="id_phone">Teléfono(s)*:</label>
            <input value="{{form.phone.value|default:""}}" id="id_phone" maxlength="100" name="phone" class="form-control" placeholder="+34 666 777 888, +34 666 999 888, ..." type="text" required>
            {{form.phone.errors}}
          </p>
          <p class="short">
            <label for="id_secondary_emails">Otros emails:</label>
            <input value="{{form.secondary_emails.value|default:""}}" id="id_secondary_emails" name="secondary_emails" class="form-control" placeholder="email@dominio.com, otroMail@dominio.com, ..." type="text" data-toggle="tooltip" data-placement="bottom" title="Revisa que el/los correo(s) esté(n) bien escrito(s)"></input>
            <small>(Opcional, y separados por comas)</small>
            {{form.secondary_emails.errors}}
          </p>
        </div>
        <div class="box">
          <h2>Información del grupo</h2>
          <p>
            <label for="id_groups">Grupo o iniciativa a la que te quieres unir:</label>
            {{form.groups}}
            {{form.groups.errors}}
          </p>

          <p>
            <label for="id_role">Rol que desempeñas*:</label>
            <input value="{{form.role.value|default:""}}" id="id_role" maxlength="100" class="form-control" placeholder="Responsable de grupo" name="role" type="text" required>
            {{form.role.errors}}
          </p>
        </div>

      </div>
      <div class="col-md-12">
        <input type="submit" value="Enviar la solicitud" class="pull-right btn btn-lg btn-warning mt1">
      </div>
    </form>
{% endblock %}

members/templates/members/thanks.html
{% extends "base.html" %}
{% load staticfiles %}

{% block breadcumb %}
<ol class="breadcrumb">
  <li><a href="{% url 'home' %}">Inicio</a></li>
  <li><a href="{% url 'members:signup' %}">Solicitud de alta en Iniciador</a></li>
  <li class="active">Gracias</li>
</ol>
{% endblock %}

{% block body %}
<h1>Gracias</h1>
<p>Pronto revisaremos la solicitud y nos pondremos en contacto contigo.</p>
{% endblock %}